package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

public class loginController {

	@FXML
    private Button btnLimpiar;

    @FXML
    private Button btnLogin;

    @FXML
    private PasswordField inputClave;

    @FXML
    private TextField inputUsuario;

    @FXML
    private Label lblBienvenido;

    @FXML
    private Label lblClave;

    @FXML
    private Label lblMensage;

    @FXML
    private Label lblUsuario;

    @FXML
    private AnchorPane pnLogin;

    @FXML
    private Label tlblTitulo;

    public loginController() {
		// TODO Auto-generated constructor stub
	}
		// Event Listener on Button[#btnLimpiar].onAction
	@FXML
	public void limpiar(ActionEvent event) {
		// TODO Autogenerated
		inputUsuario.setText("");
		inputClave.setText("");
		lblMensage.setText("");
	}
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
		String userName = inputUsuario.getText();
		String clave = inputClave.getText();
		if (userName.equals("test") && clave.equals("test")) {
			inputUsuario.setVisible(false);
			inputClave.setVisible(false);
			lblMensage.setVisible(false);
			tlblTitulo.setVisible(false);
			lblClave.setVisible(false);
			lblUsuario.setVisible(false);
			btnLimpiar.setVisible(false);
			btnLogin.setVisible(false);

			lblBienvenido.setVisible(true);
			lblBienvenido.setText("Bienvenido");
			
		} else {
			lblMensage.setText("Usario / Clave invalido");			
		}
	}
}
